### PR TITLE
switch windows to CRT, throw out old virtual

### PR DESCRIPTION
**Pull request by steffengy**
Get the windows builds rolling, tests pass.

### CODE REVIEW

**Comment by cznic** [comment]
Thanks! I will test and review after the changes this PR depends on get in.

**Comment by steffengy** [comment]
AFAIK now everything else landed.

**Comment by cznic** [comment]
> AFAIK now everything else landed.

Thanks, agreed. I will be ready in few tens of minutes.

**Review by cznic — APPROVED** [review]
Tested on linux_{386,amd64}, including pre and post `go generate`, everything works: LGTM.

Thank you very much for your excellent work!

**Pull request merged**
